#cloud-config
users:
  - name: admin_user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAA...tu-clave-ssh-publica

ssh_pwauth: false

packages:
  - firewalld
  - fail2ban

runcmd:
  - systemctl enable firewalld
  - systemctl start firewalld
  - firewall-cmd --permanent --add-service=ssh
  - firewall-cmd --permanent --add-service=http
  - firewall-cmd --permanent --add-service=https
  - firewall-cmd --reload
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - echo "[sshd]" > /etc/fail2ban/jail.local
  - echo "enabled = true" >> /etc/fail2ban/jail.local
  - systemctl restart fail2ban