#cloud-config
users:
  - name: ${USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

ssh_pwauth: false

packages:
  - tar
  - gcc
  - make
  - epel-release
  - firewalld
  - yum-utils
  - git
  - nginx

runcmd:
  # Actualizar el sistema
  - dnf update -y && dnf upgrade -y
  
  # Configuración de firewalld
  - systemctl enable firewalld
  - systemctl start firewalld
  - firewall-cmd --permanent --add-service=ssh
  - firewall-cmd --permanent --add-service=http
  - firewall-cmd --permanent --add-service=https
  - firewall-cmd --reload

  # Configuración de fail2ban
  - dnf install -y fail2ban fail2ban-firewalld
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - touch /etc/fail2ban/jail.local
  - echo "[DEFAULT]" >> /etc/fail2ban/jail.local
  - echo "ignoreip = 127.0.0.1/8 ::1" >> /etc/fail2ban/jail.local
  - echo "bantime = 1h" >> /etc/fail2ban/jail.local
  - echo "findtime = 1h" >> /etc/fail2ban/jail.local
  - echo "maxretry = 5" >> /etc/fail2ban/jail.local
  - mv /etc/fail2ban/jail.d/00-firewalld.conf /etc/fail2ban/jail.d/00-firewalld.local
  - touch /etc/fail2ban/jail.d/sshd.local
  - echo "[sshd]" > /etc/fail2ban/jail.d/sshd.local
  - echo "enabled = true" >> /etc/fail2ban/jail.d/sshd.local
  - echo "bantime = 600" >> /etc/fail2ban/jail.d/sshd.local
  - echo "findtime = 600" >> /etc/fail2ban/jail.d/sshd.local
  - echo "maxretry = 3" >> /etc/fail2ban/jail.d/sshd.local
  - echo "filter = sshd" >> /etc/fail2ban/jail.d/sshd.local
  - echo "logpath = /var/log/ssh-auth.log" >> /etc/fail2ban/jail.d/sshd.local
  - systemctl restart fail2ban

  # Instalación de Docker
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - systemctl start docker

  # Instalación de Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

  # Verificar instalación de Docker y Docker Compose
  - docker --version
  - docker-compose --version

  # Configuración de Nginx
  - systemctl enable nginx
  - systemctl start nginx

  # Copiar claves SSH de root a admin_mkl
  - mkdir -p /home/${USER}/.ssh
  - cp /root/.ssh/authorized_keys /home/${USER}/.ssh/authorized_keys
  - chown -R ${USER}:${USER} /home/${USER}/.ssh
  - chmod 700 /home/${USER}/.ssh
  - chmod 600 /home/${USER}/.ssh/authorized_keys